namespace DivaHook.Injection
{
    internal enum GlutCursor : int
    {
        GLUT_CURSOR_RIGHT_ARROW = 0,
        GLUT_CURSOR_LEFT_ARROW = 1,
        GLUT_CURSOR_INFO = 2,
        GLUT_CURSOR_DESTROY = 3,
        GLUT_CURSOR_HELP = 4,
        GLUT_CURSOR_CYCLE = 5,
        GLUT_CURSOR_SPRAY = 6,
        GLUT_CURSOR_WAIT = 7,
        GLUT_CURSOR_TEXT = 8,
        GLUT_CURSOR_CROSSHAIR = 9,
        GLUT_CURSOR_UP_DOWN = 10,
        GLUT_CURSOR_LEFT_RIGHT = 11,
        GLUT_CURSOR_TOP_SIDE = 12,
        GLUT_CURSOR_BOTTOM_SIDE = 13,
        GLUT_CURSOR_LEFT_SIDE = 14,
        GLUT_CURSOR_RIGHT_SIDE = 15,
        GLUT_CURSOR_TOP_LEFT_CORNER = 16,
        GLUT_CURSOR_TOP_RIGHT_CORNER = 17,
        GLUT_CURSOR_BOTTOM_RIGHT_CORNER = 18,
        GLUT_CURSOR_BOTTOM_LEFT_CORNER = 19,
        GLUT_CURSOR_INHERIT = 100,
        GLUT_CURSOR_NONE = 101,
        GLUT_CURSOR_FULL_CROSSHAIR = 102,
    }
}
